# .golangci.yml — v2.1
version: "2.1"

linters:
  # keep everything off unless we enable it
  default: none

  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck     # gosimple + stylecheck are bundled here
    - typecheck
    - unused
    - nilnil
    - nilerr
    - errorsnew

  settings:
    custom:
      errorsnew:
        path: "./errorsnew.so"