# See https://golangci-lint.run/v2.1/configuration/ for v2.1 config reference

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - nilnil
    - nilerr
    - errorsnew

plugins:
  - name: errorsnew
    path: "./errorsnew.so"
    module: github.com/otterize/intents-operator/linters
version: v2.1
