version: "2"
linters:
  default: none
  enable:
    - errcheck
    - errorsnew
    - govet
    - ineffassign
    - nilerr
    - nilnil
    - staticcheck
    - unused
  settings:
    custom:
      errorsnew:
        path: ./errorsnew.so
        original-url: github.com/otterize/intents-operator/linters
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
