# .golangci.yml – v2.1 syntax
version: "2.1"

linters:
  # v1 `disable-all: true` ⇒ v2 `default: none`
  default: none

  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck   # includes stylecheck + gosimple in v2
    - typecheck
    - unused
    - nilnil
    - nilerr
    - errorsnew     # custom plugin


plugins:
 - name: errorsnew          # the linter’s ID – must match what you `enable`
   path: "./errorsnew.so"   # same .so you used before
   module: github.com/otterize/intents-operator/linters
