apiVersion: k8s.otterize.com/v1alpha1
kind: ClientIntents
metadata:
  name: http-client-test
  namespace: http-server-test
spec:
  service:
    name: client
  calls:
    - name: server
      type: HTTP
