apiVersion: k8s.otterize.com/v1alpha3
kind: ClientIntents
metadata:
  name: client
  namespace:  otterize-tutorial-npol
spec:
  service:
    kind: Deployment
    name: client
  calls:
    - name: server
      kind: Service