# permissions for end users to edit kafkaserverconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kafkaserverconfig-editor-role
rules:
- apiGroups:
  - otterize.com
  resources:
  - kafkaserverconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - otterize.com
  resources:
  - kafkaserverconfigs/status
  verbs:
  - get
