# permissions for end users to view kafkaserverconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kafkaserverconfig-viewer-role
rules:
- apiGroups:
  - otterize.com
  resources:
  - kafkaserverconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - otterize.com
  resources:
  - kafkaserverconfigs/status
  verbs:
  - get
