// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package mock_iampolicyagents is a generated GoMock package.
package mock_iampolicyagents

import (
	context "context"
	reflect "reflect"

	v2alpha1 "github.com/otterize/intents-operator/src/operator/api/v2alpha1"
	gomock "go.uber.org/mock/gomock"
	v1 "k8s.io/api/core/v1"
)

// MockIAMPolicyAgent is a mock of IAMPolicyAgent interface.
type MockIAMPolicyAgent struct {
	ctrl     *gomock.Controller
	recorder *MockIAMPolicyAgentMockRecorder
}

// MockIAMPolicyAgentMockRecorder is the mock recorder for MockIAMPolicyAgent.
type MockIAMPolicyAgentMockRecorder struct {
	mock *MockIAMPolicyAgent
}

// NewMockIAMPolicyAgent creates a new mock instance.
func NewMockIAMPolicyAgent(ctrl *gomock.Controller) *MockIAMPolicyAgent {
	mock := &MockIAMPolicyAgent{ctrl: ctrl}
	mock.recorder = &MockIAMPolicyAgentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAMPolicyAgent) EXPECT() *MockIAMPolicyAgentMockRecorder {
	return m.recorder
}

// AddRolePolicyFromIntents mocks base method.
func (m *MockIAMPolicyAgent) AddRolePolicyFromIntents(ctx context.Context, namespace, accountName, intentsServiceName string, intents v2alpha1.ClientIntents, filteredTargets []v2alpha1.Target, pod v1.Pod) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRolePolicyFromIntents", ctx, namespace, accountName, intentsServiceName, intents, filteredTargets, pod)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddRolePolicyFromIntents indicates an expected call of AddRolePolicyFromIntents.
func (mr *MockIAMPolicyAgentMockRecorder) AddRolePolicyFromIntents(ctx, namespace, accountName, intentsServiceName, intents, filteredTargets, pod interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRolePolicyFromIntents", reflect.TypeOf((*MockIAMPolicyAgent)(nil).AddRolePolicyFromIntents), ctx, namespace, accountName, intentsServiceName, intents, filteredTargets, pod)
}

// AppliesOnPod mocks base method.
func (m *MockIAMPolicyAgent) AppliesOnPod(pod *v1.Pod) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppliesOnPod", pod)
	ret0, _ := ret[0].(bool)
	return ret0
}

// AppliesOnPod indicates an expected call of AppliesOnPod.
func (mr *MockIAMPolicyAgentMockRecorder) AppliesOnPod(pod interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppliesOnPod", reflect.TypeOf((*MockIAMPolicyAgent)(nil).AppliesOnPod), pod)
}

// DeleteRolePolicyFromIntents mocks base method.
func (m *MockIAMPolicyAgent) DeleteRolePolicyFromIntents(ctx context.Context, intents v2alpha1.ClientIntents) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRolePolicyFromIntents", ctx, intents)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRolePolicyFromIntents indicates an expected call of DeleteRolePolicyFromIntents.
func (mr *MockIAMPolicyAgentMockRecorder) DeleteRolePolicyFromIntents(ctx, intents interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRolePolicyFromIntents", reflect.TypeOf((*MockIAMPolicyAgent)(nil).DeleteRolePolicyFromIntents), ctx, intents)
}

// IntentType mocks base method.
func (m *MockIAMPolicyAgent) IntentType() v2alpha1.IntentType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IntentType")
	ret0, _ := ret[0].(v2alpha1.IntentType)
	return ret0
}

// IntentType indicates an expected call of IntentType.
func (mr *MockIAMPolicyAgentMockRecorder) IntentType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IntentType", reflect.TypeOf((*MockIAMPolicyAgent)(nil).IntentType))
}
