// Code generated by MockGen. DO NOT EDIT.
// Source: ../istiopolicy/admin.go

// Package intentsreconcilersmocks is a generated GoMock package.
package intentsreconcilersmocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	v1alpha2 "github.com/otterize/intents-operator/src/operator/api/v1alpha2"
)

// MockAdmin is a mock of Admin interface.
type MockAdmin struct {
	ctrl     *gomock.Controller
	recorder *MockAdminMockRecorder
}

// MockAdminMockRecorder is the mock recorder for MockAdmin.
type MockAdminMockRecorder struct {
	mock *MockAdmin
}

// NewMockAdmin creates a new mock instance.
func NewMockAdmin(ctrl *gomock.Controller) *MockAdmin {
	mock := &MockAdmin{ctrl: ctrl}
	mock.recorder = &MockAdminMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdmin) EXPECT() *MockAdminMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAdmin) Create(ctx context.Context, clientIntents *v1alpha2.ClientIntents, clientServiceAccount string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, clientIntents, clientServiceAccount)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAdminMockRecorder) Create(ctx, clientIntents, clientServiceAccount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAdmin)(nil).Create), ctx, clientIntents, clientServiceAccount)
}

// DeleteAll mocks base method.
func (m *MockAdmin) DeleteAll(ctx context.Context, clientIntents *v1alpha2.ClientIntents) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAll", ctx, clientIntents)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAll indicates an expected call of DeleteAll.
func (mr *MockAdminMockRecorder) DeleteAll(ctx, clientIntents interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAll", reflect.TypeOf((*MockAdmin)(nil).DeleteAll), ctx, clientIntents)
}

// UpdateIntentsStatus mocks base method.
func (m *MockAdmin) UpdateIntentsStatus(ctx context.Context, clientIntents *v1alpha2.ClientIntents, clientServiceAccount string, missingSideCar bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateIntentsStatus", ctx, clientIntents, clientServiceAccount, missingSideCar)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateIntentsStatus indicates an expected call of UpdateIntentsStatus.
func (mr *MockAdminMockRecorder) UpdateIntentsStatus(ctx, clientIntents, clientServiceAccount, missingSideCar interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateIntentsStatus", reflect.TypeOf((*MockAdmin)(nil).UpdateIntentsStatus), ctx, clientIntents, clientServiceAccount, missingSideCar)
}

// UpdateServerSidecar mocks base method.
func (m *MockAdmin) UpdateServerSidecar(ctx context.Context, clientIntents *v1alpha2.ClientIntents, serverName string, missingSideCar bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateServerSidecar", ctx, clientIntents, serverName, missingSideCar)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateServerSidecar indicates an expected call of UpdateServerSidecar.
func (mr *MockAdminMockRecorder) UpdateServerSidecar(ctx, clientIntents, serverName, missingSideCar interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateServerSidecar", reflect.TypeOf((*MockAdmin)(nil).UpdateServerSidecar), ctx, clientIntents, serverName, missingSideCar)
}
