---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otterize-pod-watcher-role
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - namespaces
    verbs:
      - get
      - update
      - list
      - watch
      - patch
  - apiGroups:
      - "apps"
    resources:
      - 'daemonsets'
      - 'replicasets'
      - 'statefulsets'
      - 'deployments'
    verbs:
      - 'get'
      - 'list'
      - 'watch'
  - apiGroups:
      - "k8s.otterize.com"
    resources:
      - clientintents
    verbs:
      - get
      - list
      - watch
      - patch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
